### ISSUE TITLE
Broker.processInvoice() won't work on transactions with the Bank

### ISSUE THREAD

**Issue by kevinjreece** [cjs-smith1993/Settlers#1]
There is currently no logic in Broker.processInvoice() to handle transactions with the Bank. We either need to add special logic for transactions including the Bank or we need to treat the Bank as just another Player in the Broker's Map of Player Numbers to Player Holdings. You may have already thought of this but I wanted to make sure it was recorded somewhere. We could make Bank extend PlayerHoldings so it could be held in the Broker's Map and still have it's special stuff.

**Comment by connorsmith256** [comment]
This is a good point. Either way would work, but it would be a little strange to have the Bank extend a class that has played monuments/knights and harbors. If you're going to treat the Bank as a PlayerHoldings, then I think the best way to accomplish it is to have both the Bank and PlayerHoldings implement a common interface that deals only with collections of resource cards and dev cards as well as mutators on those that can withdraw and deposit cards.

Either that, or just use special logic for when the bank is part of an invoice transaction.

**Comment by kevinjreece** [comment]
That's what I didn't like about it. But I think the common interface is the best way to do it. Interfaces are pretty straightforward and I think its worth it to make the actual "trading" logic as simple as possible.
